using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using Siticone.UI.WinForms;

namespace SUPER
{
	public sealed class status : Form
	{
		private IContainer dashboard = AssistantHelper.dashboard;

		private SiticoneGroupBox siticoneGroupBox3;

		private SiticoneRadioButton fivemtempb;

		private PictureBox pictureBox1;

		private SiticoneRadioButton siticoneRadioButton4;

		private SiticoneRadioButton siticoneRadioButton3;

		private SiticoneRadioButton siticoneRadioButton2;

		private SiticoneGroupBox siticoneGroupBox2;

		private SiticoneGroupBox siticoneGroupBox1;

		private SiticoneRadioButton siticoneRadioButton5;

		private SiticoneGroupBox siticoneGroupBox4;

		private SiticoneGroupBox siticoneGroupBox6;

		private SiticoneRadioButton siticoneRadioButton9;

		private SiticoneRadioButton siticoneRadioButton10;

		private SiticoneRadioButton siticoneRadioButton11;

		private SiticoneRadioButton siticoneRadioButton18;

		private SiticoneRadioButton siticoneRadioButton17;

		private SiticoneRadioButton siticoneRadioButton16;

		private SiticoneRadioButton siticoneRadioButton15;

		private SiticoneRadioButton siticoneRadioButton14;

		private SiticoneRadioButton siticoneRadioButton13;

		private SiticoneRadioButton siticoneRadioButton6;

		private SiticoneRadioButton siticoneRadioButton12;

		private SiticoneRadioButton siticoneRadioButton8;

		private SiticoneRadioButton siticoneRadioButton7;

		private SiticoneGroupBox siticoneGroupBox8;

		private SiticoneRadioButton siticoneRadioButton28;

		private SiticoneRadioButton siticoneRadioButton25;

		private SiticoneRadioButton siticoneRadioButton24;

		private SiticoneRadioButton siticoneRadioButton23;

		private SiticoneRadioButton siticoneRadioButton22;

		private SiticoneRadioButton siticoneRadioButton26;

		private SiticoneRadioButton siticoneRadioButton27;

		private SiticoneRadioButton siticoneRadioButton19;

		private SiticoneRadioButton siticoneRadioButton20;

		private SiticoneRadioButton siticoneRadioButton21;

		private SiticoneGroupBox siticoneGroupBox7;

		private SiticoneRadioButton siticoneRadioButton33;

		private SiticoneRadioButton siticoneRadioButton34;

		private SiticoneRadioButton siticoneRadioButton38;

		private SiticoneRadioButton siticoneRadioButton30;

		private Label label1;

		public status()
		{
			MainLoad();
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing && dashboard > AssistantHelper.dashboard)
				dashboard.Dispose();
			base.Dispose(disposing);
		}

		private void MainLoad()
		{
			ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(status));
			siticoneGroupBox3 = new SiticoneGroupBox();
			siticoneGroupBox2 = new SiticoneGroupBox();
			siticoneRadioButton5 = new SiticoneRadioButton();
			siticoneRadioButton3 = new SiticoneRadioButton();
			siticoneGroupBox1 = new SiticoneGroupBox();
			siticoneRadioButton4 = new SiticoneRadioButton();
			siticoneRadioButton2 = new SiticoneRadioButton();
			fivemtempb = new SiticoneRadioButton();
			siticoneGroupBox4 = new SiticoneGroupBox();
			siticoneGroupBox6 = new SiticoneGroupBox();
			siticoneRadioButton8 = new SiticoneRadioButton();
			label1 = new Label();
			siticoneRadioButton30 = new SiticoneRadioButton();
			siticoneRadioButton7 = new SiticoneRadioButton();
			siticoneRadioButton18 = new SiticoneRadioButton();
			siticoneRadioButton17 = new SiticoneRadioButton();
			siticoneRadioButton16 = new SiticoneRadioButton();
			siticoneRadioButton15 = new SiticoneRadioButton();
			siticoneRadioButton14 = new SiticoneRadioButton();
			siticoneRadioButton13 = new SiticoneRadioButton();
			siticoneRadioButton6 = new SiticoneRadioButton();
			siticoneRadioButton12 = new SiticoneRadioButton();
			siticoneRadioButton9 = new SiticoneRadioButton();
			siticoneRadioButton10 = new SiticoneRadioButton();
			siticoneRadioButton11 = new SiticoneRadioButton();
			siticoneGroupBox8 = new SiticoneGroupBox();
			siticoneRadioButton28 = new SiticoneRadioButton();
			siticoneRadioButton25 = new SiticoneRadioButton();
			siticoneRadioButton24 = new SiticoneRadioButton();
			siticoneRadioButton23 = new SiticoneRadioButton();
			siticoneRadioButton22 = new SiticoneRadioButton();
			siticoneRadioButton26 = new SiticoneRadioButton();
			siticoneRadioButton27 = new SiticoneRadioButton();
			siticoneRadioButton19 = new SiticoneRadioButton();
			siticoneRadioButton20 = new SiticoneRadioButton();
			siticoneRadioButton21 = new SiticoneRadioButton();
			siticoneGroupBox7 = new SiticoneGroupBox();
			siticoneRadioButton33 = new SiticoneRadioButton();
			siticoneRadioButton34 = new SiticoneRadioButton();
			siticoneRadioButton38 = new SiticoneRadioButton();
			pictureBox1 = new PictureBox();
			siticoneGroupBox3.SuspendLayout();
			siticoneGroupBox2.SuspendLayout();
			siticoneGroupBox1.SuspendLayout();
			siticoneGroupBox4.SuspendLayout();
			siticoneGroupBox6.SuspendLayout();
			siticoneGroupBox8.SuspendLayout();
			siticoneGroupBox7.SuspendLayout();
			((ISupportInitialize)pictureBox1).BeginInit();
			SuspendLayout();
			siticoneGroupBox3.BorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox3.Controls.Add(siticoneGroupBox2);
			siticoneGroupBox3.Controls.Add(pictureBox1);
			siticoneGroupBox3.Controls.Add(siticoneGroupBox1);
			siticoneGroupBox3.CustomBorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox3.FillColor = Color.FromArgb(25, 26, 30);
			siticoneGroupBox3.Font = new Font("Segoe UI", 9f);
			siticoneGroupBox3.ForeColor = Color.FromArgb(125, 137, 149);
			siticoneGroupBox3.Location = new Point(9, 18);
			siticoneGroupBox3.Name = "siticoneGroupBox3";
			siticoneGroupBox3.ShadowDecoration.Parent = siticoneGroupBox3;
			siticoneGroupBox3.Size = new Size(539, 250);
			siticoneGroupBox3.TabIndex = 97;
			siticoneGroupBox3.Text = "FiveM Spoofing Status";
			siticoneGroupBox2.BorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox2.Controls.Add(siticoneRadioButton5);
			siticoneGroupBox2.Controls.Add(siticoneRadioButton3);
			siticoneGroupBox2.CustomBorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox2.FillColor = Color.FromArgb(25, 26, 30);
			siticoneGroupBox2.Font = new Font("Segoe UI", 9f);
			siticoneGroupBox2.ForeColor = Color.FromArgb(125, 137, 149);
			siticoneGroupBox2.Location = new Point(282, 112);
			siticoneGroupBox2.Name = "siticoneGroupBox2";
			siticoneGroupBox2.ShadowDecoration.Parent = siticoneGroupBox2;
			siticoneGroupBox2.Size = new Size(248, 127);
			siticoneGroupBox2.TabIndex = 103;
			siticoneGroupBox2.Text = "Testing Componments:";
			siticoneRadioButton5.AutoCheck = false;
			siticoneRadioButton5.AutoSize = true;
			siticoneRadioButton5.Checked = true;
			siticoneRadioButton5.CheckedState.BorderColor = Color.Red;
			siticoneRadioButton5.CheckedState.BorderThickness = 1;
			siticoneRadioButton5.CheckedState.FillColor = Color.DarkRed;
			siticoneRadioButton5.CheckedState.InnerColor = Color.DarkRed;
			siticoneRadioButton5.CheckedState.InnerOffset = 1;
			siticoneRadioButton5.Location = new Point(12, 71);
			siticoneRadioButton5.Name = "siticoneRadioButton5";
			siticoneRadioButton5.Size = new Size(97, 19);
			siticoneRadioButton5.TabIndex = 101;
			siticoneRadioButton5.Text = "NVME Drivers";
			siticoneRadioButton5.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton5.UncheckedState.BorderThickness = 2;
			siticoneRadioButton5.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton5.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton5.UseVisualStyleBackColor = true;
			siticoneRadioButton3.AutoCheck = false;
			siticoneRadioButton3.AutoSize = true;
			siticoneRadioButton3.Checked = true;
			siticoneRadioButton3.CheckedState.BorderColor = Color.Red;
			siticoneRadioButton3.CheckedState.BorderThickness = 1;
			siticoneRadioButton3.CheckedState.FillColor = Color.DarkRed;
			siticoneRadioButton3.CheckedState.InnerColor = Color.DarkRed;
			siticoneRadioButton3.CheckedState.InnerOffset = 1;
			siticoneRadioButton3.Location = new Point(12, 46);
			siticoneRadioButton3.Name = "siticoneRadioButton3";
			siticoneRadioButton3.Size = new Size(151, 19);
			siticoneRadioButton3.TabIndex = 100;
			siticoneRadioButton3.Text = "Windows Version : 21H2";
			siticoneRadioButton3.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton3.UncheckedState.BorderThickness = 2;
			siticoneRadioButton3.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton3.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton3.UseVisualStyleBackColor = true;
			siticoneGroupBox1.BorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox1.Controls.Add(siticoneRadioButton4);
			siticoneGroupBox1.Controls.Add(siticoneRadioButton2);
			siticoneGroupBox1.Controls.Add(fivemtempb);
			siticoneGroupBox1.CustomBorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox1.FillColor = Color.FromArgb(25, 26, 30);
			siticoneGroupBox1.Font = new Font("Segoe UI", 9f);
			siticoneGroupBox1.ForeColor = Color.FromArgb(125, 137, 149);
			siticoneGroupBox1.Location = new Point(8, 112);
			siticoneGroupBox1.Name = "siticoneGroupBox1";
			siticoneGroupBox1.ShadowDecoration.Parent = siticoneGroupBox1;
			siticoneGroupBox1.Size = new Size(248, 127);
			siticoneGroupBox1.TabIndex = 102;
			siticoneGroupBox1.Text = "Working Componments:";
			siticoneRadioButton4.AutoCheck = false;
			siticoneRadioButton4.AutoSize = true;
			siticoneRadioButton4.Checked = true;
			siticoneRadioButton4.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton4.CheckedState.BorderThickness = 1;
			siticoneRadioButton4.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton4.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton4.CheckedState.InnerOffset = 1;
			siticoneRadioButton4.Location = new Point(10, 96);
			siticoneRadioButton4.Name = "siticoneRadioButton4";
			siticoneRadioButton4.Size = new Size(169, 19);
			siticoneRadioButton4.TabIndex = 101;
			siticoneRadioButton4.Text = "Windows Platform: 8/10/11";
			siticoneRadioButton4.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton4.UncheckedState.BorderThickness = 2;
			siticoneRadioButton4.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton4.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton4.UseVisualStyleBackColor = true;
			siticoneRadioButton2.AutoCheck = false;
			siticoneRadioButton2.AutoSize = true;
			siticoneRadioButton2.Checked = true;
			siticoneRadioButton2.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton2.CheckedState.BorderThickness = 1;
			siticoneRadioButton2.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton2.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton2.CheckedState.InnerOffset = 1;
			siticoneRadioButton2.Location = new Point(10, 71);
			siticoneRadioButton2.Name = "siticoneRadioButton2";
			siticoneRadioButton2.Size = new Size(186, 19);
			siticoneRadioButton2.TabIndex = 99;
			siticoneRadioButton2.Text = "Windows Version : 1803 - 21H1";
			siticoneRadioButton2.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton2.UncheckedState.BorderThickness = 2;
			siticoneRadioButton2.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton2.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton2.UseVisualStyleBackColor = true;
			fivemtempb.AutoCheck = false;
			fivemtempb.AutoSize = true;
			fivemtempb.Checked = true;
			fivemtempb.CheckedState.BorderColor = Color.Lime;
			fivemtempb.CheckedState.BorderThickness = 1;
			fivemtempb.CheckedState.FillColor = Color.DarkGreen;
			fivemtempb.CheckedState.InnerColor = Color.DarkGreen;
			fivemtempb.CheckedState.InnerOffset = 1;
			fivemtempb.Location = new Point(10, 46);
			fivemtempb.Name = "fivemtempb";
			fivemtempb.Size = new Size(178, 19);
			fivemtempb.TabIndex = 97;
			fivemtempb.Text = "AMD-NVIDIA Graphics Driver";
			fivemtempb.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			fivemtempb.UncheckedState.BorderThickness = 2;
			fivemtempb.UncheckedState.FillColor = Color.Transparent;
			fivemtempb.UncheckedState.InnerColor = Color.Transparent;
			fivemtempb.UseVisualStyleBackColor = true;
			siticoneGroupBox4.BorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox4.Controls.Add(siticoneGroupBox6);
			siticoneGroupBox4.CustomBorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox4.FillColor = Color.FromArgb(25, 26, 30);
			siticoneGroupBox4.Font = new Font("Segoe UI", 9f);
			siticoneGroupBox4.ForeColor = Color.FromArgb(125, 137, 149);
			siticoneGroupBox4.Location = new Point(550, 18);
			siticoneGroupBox4.Name = "siticoneGroupBox4";
			siticoneGroupBox4.ShadowDecoration.Parent = siticoneGroupBox4;
			siticoneGroupBox4.Size = new Size(304, 580);
			siticoneGroupBox4.TabIndex = 104;
			siticoneGroupBox4.Text = "System Spoofing Status";
			siticoneGroupBox6.BorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton8);
			siticoneGroupBox6.Controls.Add(label1);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton30);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton7);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton18);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton17);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton16);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton15);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton14);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton13);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton6);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton12);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton9);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton10);
			siticoneGroupBox6.Controls.Add(siticoneRadioButton11);
			siticoneGroupBox6.CustomBorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox6.FillColor = Color.FromArgb(25, 26, 30);
			siticoneGroupBox6.Font = new Font("Segoe UI", 9f);
			siticoneGroupBox6.ForeColor = Color.FromArgb(125, 137, 149);
			siticoneGroupBox6.Location = new Point(7, 49);
			siticoneGroupBox6.Name = "siticoneGroupBox6";
			siticoneGroupBox6.ShadowDecoration.Parent = siticoneGroupBox6;
			siticoneGroupBox6.Size = new Size(287, 523);
			siticoneGroupBox6.TabIndex = 102;
			siticoneGroupBox6.Text = "Working Componments:";
			siticoneRadioButton8.AutoCheck = false;
			siticoneRadioButton8.AutoSize = true;
			siticoneRadioButton8.Checked = true;
			siticoneRadioButton8.CheckedState.BorderColor = Color.Red;
			siticoneRadioButton8.CheckedState.BorderThickness = 1;
			siticoneRadioButton8.CheckedState.FillColor = Color.DarkRed;
			siticoneRadioButton8.CheckedState.InnerColor = Color.DarkRed;
			siticoneRadioButton8.CheckedState.InnerOffset = 1;
			siticoneRadioButton8.Location = new Point(10, 492);
			siticoneRadioButton8.Name = "siticoneRadioButton8";
			siticoneRadioButton8.Size = new Size(142, 19);
			siticoneRadioButton8.TabIndex = 97;
			siticoneRadioButton8.Text = "NVME (IDE Controller)";
			siticoneRadioButton8.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton8.UncheckedState.BorderThickness = 2;
			siticoneRadioButton8.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton8.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton8.UseVisualStyleBackColor = true;
			label1.AutoSize = true;
			label1.Location = new Point(24, 365);
			label1.Name = "label1";
			label1.Size = new Size(242, 120);
			label1.TabIndex = 113;
			label1.Text = componentResourceManager.GetString("label1.Text");
			siticoneRadioButton30.AutoCheck = false;
			siticoneRadioButton30.AutoSize = true;
			siticoneRadioButton30.Checked = true;
			siticoneRadioButton30.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton30.CheckedState.BorderThickness = 1;
			siticoneRadioButton30.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton30.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton30.CheckedState.InnerOffset = 1;
			siticoneRadioButton30.Location = new Point(10, 346);
			siticoneRadioButton30.Name = "siticoneRadioButton30";
			siticoneRadioButton30.Size = new Size(223, 19);
			siticoneRadioButton30.TabIndex = 112;
			siticoneRadioButton30.Text = "Randomized Windows Configuration;";
			siticoneRadioButton30.TextAlign = ContentAlignment.BottomLeft;
			siticoneRadioButton30.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton30.UncheckedState.BorderThickness = 2;
			siticoneRadioButton30.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton30.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton30.UseVisualStyleBackColor = true;
			siticoneRadioButton7.AutoCheck = false;
			siticoneRadioButton7.AutoSize = true;
			siticoneRadioButton7.Checked = true;
			siticoneRadioButton7.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton7.CheckedState.BorderThickness = 1;
			siticoneRadioButton7.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton7.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton7.CheckedState.InnerOffset = 1;
			siticoneRadioButton7.Location = new Point(10, 321);
			siticoneRadioButton7.Name = "siticoneRadioButton7";
			siticoneRadioButton7.Size = new Size(181, 19);
			siticoneRadioButton7.TabIndex = 110;
			siticoneRadioButton7.Text = "Windows System Information";
			siticoneRadioButton7.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton7.UncheckedState.BorderThickness = 2;
			siticoneRadioButton7.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton7.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton7.UseVisualStyleBackColor = true;
			siticoneRadioButton18.AutoCheck = false;
			siticoneRadioButton18.AutoSize = true;
			siticoneRadioButton18.Checked = true;
			siticoneRadioButton18.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton18.CheckedState.BorderThickness = 1;
			siticoneRadioButton18.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton18.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton18.CheckedState.InnerOffset = 1;
			siticoneRadioButton18.Location = new Point(10, 296);
			siticoneRadioButton18.Name = "siticoneRadioButton18";
			siticoneRadioButton18.Size = new Size(199, 19);
			siticoneRadioButton18.TabIndex = 109;
			siticoneRadioButton18.Text = "Basic Links (xbox/mac/windows)";
			siticoneRadioButton18.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton18.UncheckedState.BorderThickness = 2;
			siticoneRadioButton18.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton18.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton18.UseVisualStyleBackColor = true;
			siticoneRadioButton17.AutoCheck = false;
			siticoneRadioButton17.AutoSize = true;
			siticoneRadioButton17.Checked = true;
			siticoneRadioButton17.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton17.CheckedState.BorderThickness = 1;
			siticoneRadioButton17.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton17.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton17.CheckedState.InnerOffset = 1;
			siticoneRadioButton17.Location = new Point(10, 271);
			siticoneRadioButton17.Name = "siticoneRadioButton17";
			siticoneRadioButton17.Size = new Size(169, 19);
			siticoneRadioButton17.TabIndex = 108;
			siticoneRadioButton17.Text = "GPU (Read FiveM for more)";
			siticoneRadioButton17.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton17.UncheckedState.BorderThickness = 2;
			siticoneRadioButton17.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton17.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton17.UseVisualStyleBackColor = true;
			siticoneRadioButton16.AutoCheck = false;
			siticoneRadioButton16.AutoSize = true;
			siticoneRadioButton16.Checked = true;
			siticoneRadioButton16.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton16.CheckedState.BorderThickness = 1;
			siticoneRadioButton16.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton16.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton16.CheckedState.InnerOffset = 1;
			siticoneRadioButton16.Location = new Point(10, 246);
			siticoneRadioButton16.Name = "siticoneRadioButton16";
			siticoneRadioButton16.Size = new Size(82, 19);
			siticoneRadioButton16.TabIndex = 107;
			siticoneRadioButton16.Text = "USB Serials";
			siticoneRadioButton16.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton16.UncheckedState.BorderThickness = 2;
			siticoneRadioButton16.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton16.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton16.UseVisualStyleBackColor = true;
			siticoneRadioButton15.AutoCheck = false;
			siticoneRadioButton15.AutoSize = true;
			siticoneRadioButton15.Checked = true;
			siticoneRadioButton15.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton15.CheckedState.BorderThickness = 1;
			siticoneRadioButton15.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton15.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton15.CheckedState.InnerOffset = 1;
			siticoneRadioButton15.Location = new Point(10, 221);
			siticoneRadioButton15.Name = "siticoneRadioButton15";
			siticoneRadioButton15.Size = new Size(155, 19);
			siticoneRadioButton15.TabIndex = 106;
			siticoneRadioButton15.Text = "Registerys / File Cleaners";
			siticoneRadioButton15.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton15.UncheckedState.BorderThickness = 2;
			siticoneRadioButton15.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton15.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton15.UseVisualStyleBackColor = true;
			siticoneRadioButton14.AutoCheck = false;
			siticoneRadioButton14.AutoSize = true;
			siticoneRadioButton14.Checked = true;
			siticoneRadioButton14.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton14.CheckedState.BorderThickness = 1;
			siticoneRadioButton14.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton14.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton14.CheckedState.InnerOffset = 1;
			siticoneRadioButton14.Location = new Point(10, 196);
			siticoneRadioButton14.Name = "siticoneRadioButton14";
			siticoneRadioButton14.Size = new Size(207, 19);
			siticoneRadioButton14.TabIndex = 105;
			siticoneRadioButton14.Text = "Peripherals (Keyboard / Monitor...)";
			siticoneRadioButton14.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton14.UncheckedState.BorderThickness = 2;
			siticoneRadioButton14.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton14.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton14.UseVisualStyleBackColor = true;
			siticoneRadioButton13.AutoCheck = false;
			siticoneRadioButton13.AutoSize = true;
			siticoneRadioButton13.Checked = true;
			siticoneRadioButton13.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton13.CheckedState.BorderThickness = 1;
			siticoneRadioButton13.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton13.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton13.CheckedState.InnerOffset = 1;
			siticoneRadioButton13.Location = new Point(10, 171);
			siticoneRadioButton13.Name = "siticoneRadioButton13";
			siticoneRadioButton13.Size = new Size(87, 19);
			siticoneRadioButton13.TabIndex = 104;
			siticoneRadioButton13.Text = "Volume ID's";
			siticoneRadioButton13.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton13.UncheckedState.BorderThickness = 2;
			siticoneRadioButton13.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton13.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton13.UseVisualStyleBackColor = true;
			siticoneRadioButton6.AutoCheck = false;
			siticoneRadioButton6.AutoSize = true;
			siticoneRadioButton6.Checked = true;
			siticoneRadioButton6.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton6.CheckedState.BorderThickness = 1;
			siticoneRadioButton6.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton6.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton6.CheckedState.InnerOffset = 1;
			siticoneRadioButton6.Location = new Point(10, 146);
			siticoneRadioButton6.Name = "siticoneRadioButton6";
			siticoneRadioButton6.Size = new Size(225, 19);
			siticoneRadioButton6.TabIndex = 103;
			siticoneRadioButton6.Text = "CPU (Centeral Proccesing Unit) Serials\r\n";
			siticoneRadioButton6.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton6.UncheckedState.BorderThickness = 2;
			siticoneRadioButton6.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton6.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton6.UseVisualStyleBackColor = true;
			siticoneRadioButton12.AutoCheck = false;
			siticoneRadioButton12.AutoSize = true;
			siticoneRadioButton12.Checked = true;
			siticoneRadioButton12.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton12.CheckedState.BorderThickness = 1;
			siticoneRadioButton12.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton12.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton12.CheckedState.InnerOffset = 1;
			siticoneRadioButton12.Location = new Point(10, 121);
			siticoneRadioButton12.Name = "siticoneRadioButton12";
			siticoneRadioButton12.Size = new Size(142, 19);
			siticoneRadioButton12.TabIndex = 102;
			siticoneRadioButton12.Text = "SMBIOS + BIOS Serials";
			siticoneRadioButton12.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton12.UncheckedState.BorderThickness = 2;
			siticoneRadioButton12.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton12.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton12.UseVisualStyleBackColor = true;
			siticoneRadioButton9.AutoCheck = false;
			siticoneRadioButton9.AutoSize = true;
			siticoneRadioButton9.Checked = true;
			siticoneRadioButton9.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton9.CheckedState.BorderThickness = 1;
			siticoneRadioButton9.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton9.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton9.CheckedState.InnerOffset = 1;
			siticoneRadioButton9.Location = new Point(10, 96);
			siticoneRadioButton9.Name = "siticoneRadioButton9";
			siticoneRadioButton9.Size = new Size(129, 19);
			siticoneRadioButton9.TabIndex = 101;
			siticoneRadioButton9.Text = "Memorychip Serials";
			siticoneRadioButton9.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton9.UncheckedState.BorderThickness = 2;
			siticoneRadioButton9.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton9.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton9.UseVisualStyleBackColor = true;
			siticoneRadioButton10.AutoCheck = false;
			siticoneRadioButton10.AutoSize = true;
			siticoneRadioButton10.Checked = true;
			siticoneRadioButton10.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton10.CheckedState.BorderThickness = 1;
			siticoneRadioButton10.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton10.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton10.CheckedState.InnerOffset = 1;
			siticoneRadioButton10.Location = new Point(10, 71);
			siticoneRadioButton10.Name = "siticoneRadioButton10";
			siticoneRadioButton10.Size = new Size(116, 19);
			siticoneRadioButton10.TabIndex = 99;
			siticoneRadioButton10.Text = "Baseboard Serials";
			siticoneRadioButton10.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton10.UncheckedState.BorderThickness = 2;
			siticoneRadioButton10.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton10.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton10.UseVisualStyleBackColor = true;
			siticoneRadioButton11.AutoCheck = false;
			siticoneRadioButton11.AutoSize = true;
			siticoneRadioButton11.Checked = true;
			siticoneRadioButton11.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton11.CheckedState.BorderThickness = 1;
			siticoneRadioButton11.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton11.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton11.CheckedState.InnerOffset = 1;
			siticoneRadioButton11.Location = new Point(10, 46);
			siticoneRadioButton11.Name = "siticoneRadioButton11";
			siticoneRadioButton11.Size = new Size(109, 19);
			siticoneRadioButton11.TabIndex = 97;
			siticoneRadioButton11.Text = "Diskdrive Serials";
			siticoneRadioButton11.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton11.UncheckedState.BorderThickness = 2;
			siticoneRadioButton11.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton11.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton11.UseVisualStyleBackColor = true;
			siticoneGroupBox8.BorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton28);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton25);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton24);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton23);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton22);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton26);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton27);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton19);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton20);
			siticoneGroupBox8.Controls.Add(siticoneRadioButton21);
			siticoneGroupBox8.CustomBorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox8.FillColor = Color.FromArgb(25, 26, 30);
			siticoneGroupBox8.Font = new Font("Segoe UI", 9f);
			siticoneGroupBox8.ForeColor = Color.FromArgb(125, 137, 149);
			siticoneGroupBox8.Location = new Point(9, 274);
			siticoneGroupBox8.Name = "siticoneGroupBox8";
			siticoneGroupBox8.ShadowDecoration.Parent = siticoneGroupBox8;
			siticoneGroupBox8.Size = new Size(539, 163);
			siticoneGroupBox8.TabIndex = 103;
			siticoneGroupBox8.Text = "Game Status";
			siticoneRadioButton28.AutoCheck = false;
			siticoneRadioButton28.AutoSize = true;
			siticoneRadioButton28.Checked = true;
			siticoneRadioButton28.CheckedState.BorderColor = Color.Yellow;
			siticoneRadioButton28.CheckedState.BorderThickness = 1;
			siticoneRadioButton28.CheckedState.FillColor = Color.Olive;
			siticoneRadioButton28.CheckedState.InnerColor = Color.Olive;
			siticoneRadioButton28.CheckedState.InnerOffset = 1;
			siticoneRadioButton28.Location = new Point(227, 71);
			siticoneRadioButton28.Name = "siticoneRadioButton28";
			siticoneRadioButton28.Size = new Size(86, 19);
			siticoneRadioButton28.TabIndex = 108;
			siticoneRadioButton28.Text = "EAC Bypass";
			siticoneRadioButton28.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton28.UncheckedState.BorderThickness = 2;
			siticoneRadioButton28.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton28.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton28.UseVisualStyleBackColor = true;
			siticoneRadioButton25.AutoCheck = false;
			siticoneRadioButton25.AutoSize = true;
			siticoneRadioButton25.Checked = true;
			siticoneRadioButton25.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton25.CheckedState.BorderThickness = 1;
			siticoneRadioButton25.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton25.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton25.CheckedState.InnerOffset = 1;
			siticoneRadioButton25.Location = new Point(146, 121);
			siticoneRadioButton25.Name = "siticoneRadioButton25";
			siticoneRadioButton25.Size = new Size(52, 19);
			siticoneRadioButton25.TabIndex = 107;
			siticoneRadioButton25.Text = "Apex";
			siticoneRadioButton25.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton25.UncheckedState.BorderThickness = 2;
			siticoneRadioButton25.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton25.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton25.UseVisualStyleBackColor = true;
			siticoneRadioButton24.AutoCheck = false;
			siticoneRadioButton24.AutoSize = true;
			siticoneRadioButton24.Checked = true;
			siticoneRadioButton24.CheckedState.BorderColor = Color.Red;
			siticoneRadioButton24.CheckedState.BorderThickness = 1;
			siticoneRadioButton24.CheckedState.FillColor = Color.DarkRed;
			siticoneRadioButton24.CheckedState.InnerColor = Color.DarkRed;
			siticoneRadioButton24.CheckedState.InnerOffset = 1;
			siticoneRadioButton24.Location = new Point(146, 96);
			siticoneRadioButton24.Name = "siticoneRadioButton24";
			siticoneRadioButton24.Size = new Size(68, 19);
			siticoneRadioButton24.TabIndex = 106;
			siticoneRadioButton24.Text = "Valorant";
			siticoneRadioButton24.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton24.UncheckedState.BorderThickness = 2;
			siticoneRadioButton24.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton24.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton24.UseVisualStyleBackColor = true;
			siticoneRadioButton23.AutoCheck = false;
			siticoneRadioButton23.AutoSize = true;
			siticoneRadioButton23.Checked = true;
			siticoneRadioButton23.CheckedState.BorderColor = Color.Red;
			siticoneRadioButton23.CheckedState.BorderThickness = 1;
			siticoneRadioButton23.CheckedState.FillColor = Color.DarkRed;
			siticoneRadioButton23.CheckedState.InnerColor = Color.DarkRed;
			siticoneRadioButton23.CheckedState.InnerOffset = 1;
			siticoneRadioButton23.Location = new Point(146, 71);
			siticoneRadioButton23.Name = "siticoneRadioButton23";
			siticoneRadioButton23.Size = new Size(48, 19);
			siticoneRadioButton23.TabIndex = 105;
			siticoneRadioButton23.Text = "Rust";
			siticoneRadioButton23.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton23.UncheckedState.BorderThickness = 2;
			siticoneRadioButton23.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton23.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton23.UseVisualStyleBackColor = true;
			siticoneRadioButton22.AutoCheck = false;
			siticoneRadioButton22.AutoSize = true;
			siticoneRadioButton22.Checked = true;
			siticoneRadioButton22.CheckedState.BorderColor = Color.Yellow;
			siticoneRadioButton22.CheckedState.BorderThickness = 1;
			siticoneRadioButton22.CheckedState.FillColor = Color.Olive;
			siticoneRadioButton22.CheckedState.InnerColor = Color.Olive;
			siticoneRadioButton22.CheckedState.InnerOffset = 1;
			siticoneRadioButton22.Location = new Point(227, 46);
			siticoneRadioButton22.Name = "siticoneRadioButton22";
			siticoneRadioButton22.Size = new Size(110, 19);
			siticoneRadioButton22.TabIndex = 104;
			siticoneRadioButton22.Text = "Warzone (COD) ";
			siticoneRadioButton22.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton22.UncheckedState.BorderThickness = 2;
			siticoneRadioButton22.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton22.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton22.UseVisualStyleBackColor = true;
			siticoneRadioButton26.AutoCheck = false;
			siticoneRadioButton26.AutoSize = true;
			siticoneRadioButton26.Checked = true;
			siticoneRadioButton26.CheckedState.BorderColor = Color.Red;
			siticoneRadioButton26.CheckedState.BorderThickness = 1;
			siticoneRadioButton26.CheckedState.FillColor = Color.DarkRed;
			siticoneRadioButton26.CheckedState.InnerColor = Color.DarkRed;
			siticoneRadioButton26.CheckedState.InnerOffset = 1;
			siticoneRadioButton26.Location = new Point(146, 46);
			siticoneRadioButton26.Name = "siticoneRadioButton26";
			siticoneRadioButton26.Size = new Size(66, 19);
			siticoneRadioButton26.TabIndex = 103;
			siticoneRadioButton26.Text = "Fortnite";
			siticoneRadioButton26.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton26.UncheckedState.BorderThickness = 2;
			siticoneRadioButton26.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton26.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton26.UseVisualStyleBackColor = true;
			siticoneRadioButton27.AutoCheck = false;
			siticoneRadioButton27.AutoSize = true;
			siticoneRadioButton27.Checked = true;
			siticoneRadioButton27.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton27.CheckedState.BorderThickness = 1;
			siticoneRadioButton27.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton27.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton27.CheckedState.InnerOffset = 1;
			siticoneRadioButton27.Location = new Point(10, 121);
			siticoneRadioButton27.Name = "siticoneRadioButton27";
			siticoneRadioButton27.Size = new Size(120, 19);
			siticoneRadioButton27.TabIndex = 102;
			siticoneRadioButton27.Text = "Rainbow Six Siege";
			siticoneRadioButton27.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton27.UncheckedState.BorderThickness = 2;
			siticoneRadioButton27.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton27.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton27.UseVisualStyleBackColor = true;
			siticoneRadioButton19.AutoCheck = false;
			siticoneRadioButton19.AutoSize = true;
			siticoneRadioButton19.Checked = true;
			siticoneRadioButton19.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton19.CheckedState.BorderThickness = 1;
			siticoneRadioButton19.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton19.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton19.CheckedState.InnerOffset = 1;
			siticoneRadioButton19.Location = new Point(10, 96);
			siticoneRadioButton19.Name = "siticoneRadioButton19";
			siticoneRadioButton19.Size = new Size(114, 19);
			siticoneRadioButton19.TabIndex = 101;
			siticoneRadioButton19.Text = "FiveM Token Ban";
			siticoneRadioButton19.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton19.UncheckedState.BorderThickness = 2;
			siticoneRadioButton19.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton19.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton19.UseVisualStyleBackColor = true;
			siticoneRadioButton20.AutoCheck = false;
			siticoneRadioButton20.AutoSize = true;
			siticoneRadioButton20.Checked = true;
			siticoneRadioButton20.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton20.CheckedState.BorderThickness = 1;
			siticoneRadioButton20.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton20.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton20.CheckedState.InnerOffset = 1;
			siticoneRadioButton20.Location = new Point(10, 71);
			siticoneRadioButton20.Name = "siticoneRadioButton20";
			siticoneRadioButton20.Size = new Size(115, 19);
			siticoneRadioButton20.TabIndex = 99;
			siticoneRadioButton20.Text = "FiveM Server Ban";
			siticoneRadioButton20.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton20.UncheckedState.BorderThickness = 2;
			siticoneRadioButton20.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton20.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton20.UseVisualStyleBackColor = true;
			siticoneRadioButton21.AutoCheck = false;
			siticoneRadioButton21.AutoSize = true;
			siticoneRadioButton21.Checked = true;
			siticoneRadioButton21.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton21.CheckedState.BorderThickness = 1;
			siticoneRadioButton21.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton21.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton21.CheckedState.InnerOffset = 1;
			siticoneRadioButton21.Location = new Point(10, 46);
			siticoneRadioButton21.Name = "siticoneRadioButton21";
			siticoneRadioButton21.Size = new Size(117, 19);
			siticoneRadioButton21.TabIndex = 97;
			siticoneRadioButton21.Text = "FiveM Global Ban";
			siticoneRadioButton21.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton21.UncheckedState.BorderThickness = 2;
			siticoneRadioButton21.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton21.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton21.UseVisualStyleBackColor = true;
			siticoneGroupBox7.BorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox7.Controls.Add(siticoneRadioButton33);
			siticoneGroupBox7.Controls.Add(siticoneRadioButton34);
			siticoneGroupBox7.Controls.Add(siticoneRadioButton38);
			siticoneGroupBox7.CustomBorderColor = Color.FromArgb(65, 71, 85);
			siticoneGroupBox7.FillColor = Color.FromArgb(25, 26, 30);
			siticoneGroupBox7.Font = new Font("Segoe UI", 9f);
			siticoneGroupBox7.ForeColor = Color.FromArgb(125, 137, 149);
			siticoneGroupBox7.Location = new Point(9, 525);
			siticoneGroupBox7.Name = "siticoneGroupBox7";
			siticoneGroupBox7.ShadowDecoration.Parent = siticoneGroupBox7;
			siticoneGroupBox7.Size = new Size(374, 73);
			siticoneGroupBox7.TabIndex = 109;
			siticoneGroupBox7.Text = "Colour Coding:";
			siticoneRadioButton33.AutoCheck = false;
			siticoneRadioButton33.AutoSize = true;
			siticoneRadioButton33.Checked = true;
			siticoneRadioButton33.CheckedState.BorderColor = Color.Yellow;
			siticoneRadioButton33.CheckedState.BorderThickness = 1;
			siticoneRadioButton33.CheckedState.FillColor = Color.Olive;
			siticoneRadioButton33.CheckedState.InnerColor = Color.Olive;
			siticoneRadioButton33.CheckedState.InnerOffset = 1;
			siticoneRadioButton33.Location = new Point(117, 46);
			siticoneRadioButton33.Name = "siticoneRadioButton33";
			siticoneRadioButton33.Size = new Size(111, 19);
			siticoneRadioButton33.TabIndex = 104;
			siticoneRadioButton33.Text = "Unkown/Testing";
			siticoneRadioButton33.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton33.UncheckedState.BorderThickness = 2;
			siticoneRadioButton33.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton33.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton33.UseVisualStyleBackColor = true;
			siticoneRadioButton34.AutoCheck = false;
			siticoneRadioButton34.AutoSize = true;
			siticoneRadioButton34.Checked = true;
			siticoneRadioButton34.CheckedState.BorderColor = Color.Red;
			siticoneRadioButton34.CheckedState.BorderThickness = 1;
			siticoneRadioButton34.CheckedState.FillColor = Color.DarkRed;
			siticoneRadioButton34.CheckedState.InnerColor = Color.DarkRed;
			siticoneRadioButton34.CheckedState.InnerOffset = 1;
			siticoneRadioButton34.Location = new Point(234, 46);
			siticoneRadioButton34.Name = "siticoneRadioButton34";
			siticoneRadioButton34.Size = new Size(124, 19);
			siticoneRadioButton34.TabIndex = 103;
			siticoneRadioButton34.Text = "100% Not Working";
			siticoneRadioButton34.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton34.UncheckedState.BorderThickness = 2;
			siticoneRadioButton34.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton34.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton34.UseVisualStyleBackColor = true;
			siticoneRadioButton38.AutoCheck = false;
			siticoneRadioButton38.AutoSize = true;
			siticoneRadioButton38.Checked = true;
			siticoneRadioButton38.CheckedState.BorderColor = Color.Lime;
			siticoneRadioButton38.CheckedState.BorderThickness = 1;
			siticoneRadioButton38.CheckedState.FillColor = Color.DarkGreen;
			siticoneRadioButton38.CheckedState.InnerColor = Color.DarkGreen;
			siticoneRadioButton38.CheckedState.InnerOffset = 1;
			siticoneRadioButton38.Location = new Point(10, 46);
			siticoneRadioButton38.Name = "siticoneRadioButton38";
			siticoneRadioButton38.Size = new Size(101, 19);
			siticoneRadioButton38.TabIndex = 97;
			siticoneRadioButton38.Text = "100% Working";
			siticoneRadioButton38.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
			siticoneRadioButton38.UncheckedState.BorderThickness = 2;
			siticoneRadioButton38.UncheckedState.FillColor = Color.Transparent;
			siticoneRadioButton38.UncheckedState.InnerColor = Color.Transparent;
			siticoneRadioButton38.UseVisualStyleBackColor = true;
			pictureBox1.Image = (Image)componentResourceManager.GetObject("pictureBox1.Image");
			pictureBox1.Location = new Point(8, 43);
			pictureBox1.Name = "pictureBox1";
			pictureBox1.Size = new Size(522, 63);
			pictureBox1.SizeMode = PictureBoxSizeMode.Zoom;
			pictureBox1.TabIndex = 1;
			pictureBox1.TabStop = false;
			base.AutoScaleDimensions = new SizeF(6f, 13f);
			base.AutoScaleMode = AutoScaleMode.Font;
			AutoScroll = true;
			BackColor = Color.FromArgb(25, 26, 30);
			base.ClientSize = new Size(873, 610);
			base.Controls.Add(siticoneGroupBox7);
			base.Controls.Add(siticoneGroupBox8);
			base.Controls.Add(siticoneGroupBox4);
			base.Controls.Add(siticoneGroupBox3);
			base.FormBorderStyle = FormBorderStyle.None;
			base.Name = "status";
			Text = "status";
			siticoneGroupBox3.ResumeLayout(false);
			siticoneGroupBox2.ResumeLayout(false);
			siticoneGroupBox2.PerformLayout();
			siticoneGroupBox1.ResumeLayout(false);
			siticoneGroupBox1.PerformLayout();
			siticoneGroupBox4.ResumeLayout(false);
			siticoneGroupBox6.ResumeLayout(false);
			siticoneGroupBox6.PerformLayout();
			siticoneGroupBox8.ResumeLayout(false);
			siticoneGroupBox8.PerformLayout();
			siticoneGroupBox7.ResumeLayout(false);
			siticoneGroupBox7.PerformLayout();
			((ISupportInitialize)pictureBox1).EndInit();
			ResumeLayout(false);
		}
	}
}
